packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - sharp

ignoredBuiltDependencies:
  - bigint-buffer
  - bufferutil
  - esbuild
  - keccak
  - protobufjs
  - secp256k1
  - utf-8-validate
  - workerd
