import { ConnectButton } from '@rainbow-me/rainbowkit'
import { Geist, Geist_Mono } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'

import { connectContainer, connectLabel } from '@/styles/connect.css'
import {
  ctas,
  footer,
  footerImage,
  footerLink,
  logo,
  main,
  mainCode,
  mainList,
  mainListItem,
  page,
  primary,
  secondary,
} from '@/styles/home.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={main}>
          <Image
            className={logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol className={mainList}>
            <li className={mainListItem}>
              Get started by editing <code className={mainCode}>src/pages/index.tsx</code>
              .
            </li>
            <li className={mainListItem}>Save and see your changes instantly.</li>
          </ol>

          <div className={connectContainer}>
            <div>
              <div className={connectLabel}>Connect Your Wallet</div>
              <ConnectButton />
            </div>
          </div>

          <div className={ctas}>
            <a
              className={primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={footer}>
          <a
            className={footerLink}
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={footerImage}
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            className={footerLink}
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={footerImage}
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            className={footerLink}
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={footerImage}
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  )
}
