export const erc721RedeemMinterAbi = [
  {
    inputs: [
      { internalType: 'contract Manager', name: '_manager', type: 'address' },
      { internalType: 'address', name: '_protocolRewards', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'ADDRESS_ZERO', type: 'error' },
  { inputs: [], name: 'ALREADY_INITIALIZED', type: 'error' },
  { inputs: [], name: 'ALREADY_REDEEMED', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ERROR_MINTING_TOKEN',
    type: 'error',
  },
  { inputs: [], name: 'INITIALIZING', type: 'error' },
  { inputs: [], name: 'INVALID_SETTINGS', type: 'error' },
  { inputs: [], name: 'INVALID_TOKEN_COUNT', type: 'error' },
  { inputs: [], name: 'INVALID_VALUE', type: 'error' },
  { inputs: [], name: 'MINT_ENDED', type: 'error' },
  { inputs: [], name: 'MINT_NOT_STARTED', type: 'error' },
  { inputs: [], name: 'NOT_INITIALIZING', type: 'error' },
  { inputs: [], name: 'NOT_MINTED', type: 'error' },
  { inputs: [], name: 'NOT_TOKEN_OWNER', type: 'error' },
  { inputs: [], name: 'NO_TOKENS_MINTED', type: 'error' },
  { inputs: [], name: 'REENTRANCY', type: 'error' },
  { inputs: [], name: 'TRANSFER_FAILED', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'version', type: 'uint256' },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'tokenContract', type: 'address' },
      {
        components: [
          { internalType: 'uint64', name: 'mintStart', type: 'uint64' },
          { internalType: 'uint64', name: 'mintEnd', type: 'uint64' },
          { internalType: 'uint64', name: 'pricePerToken', type: 'uint64' },
          { internalType: 'address', name: 'redeemToken', type: 'address' },
        ],
        indexed: false,
        internalType: 'struct ERC721RedeemMinter.RedeemSettings',
        name: 'redeemSettings',
        type: 'tuple',
      },
    ],
    name: 'MinterSet',
    type: 'event',
  },
  {
    inputs: [],
    name: 'BUILDER_DAO_FEE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
    ],
    name: 'getTotalFeesForMint',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
    ],
    name: 'mintFromReserve',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'redeemSettings',
    outputs: [
      { internalType: 'uint64', name: 'mintStart', type: 'uint64' },
      { internalType: 'uint64', name: 'mintEnd', type: 'uint64' },
      { internalType: 'uint64', name: 'pricePerToken', type: 'uint64' },
      { internalType: 'address', name: 'redeemToken', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'redeemed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'tokenContract', type: 'address' }],
    name: 'resetMintSettings',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      {
        components: [
          { internalType: 'uint64', name: 'mintStart', type: 'uint64' },
          { internalType: 'uint64', name: 'mintEnd', type: 'uint64' },
          { internalType: 'uint64', name: 'pricePerToken', type: 'uint64' },
          { internalType: 'address', name: 'redeemToken', type: 'address' },
        ],
        internalType: 'struct ERC721RedeemMinter.RedeemSettings',
        name: 'settings',
        type: 'tuple',
      },
    ],
    name: 'setMintSettings',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
