export const WALLET_CONNECT_PROJECT_ID: string =
  process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID!
export const WALLET_CONNECT_METADATA: string =
  process.env.NEXT_PUBLIC_WALLET_CONNECT_METADATA!
